### ISSUE TITLE
PI code checklist

### ISSUE THREAD

**Issue by aremazeilles** [STEPbySTEPproj/Protocol_biomechanics#1]
FYI, the list of items I need to check for considering the code as eurobench-compatible:

- [x] 1. Readme available (purpose, install, use, acknowledgment)
- [x] 2. identify test files (input --> output)
- [x] 3. confirm main program structure (input, output)
- [x] 4. check input-output file format
- [x] 5. insert docker generation files (TEC)
- [x] 6. insert CI process (TEC)
- [x] 7. insert docker hub secret (TEC)
- [x] 8. double check template spec again

We will do so progressively

**Comment by aremazeilles** [comment]
Ping @dborro 

FYI, I made a fork of your repository in the Eurobench namespace:
https://github.com/eurobench/pi_sbs_biomechanics

I have to keep it up to date.
Then, every-time I make a release, it is automatically brought to docker:

https://hub.docker.com/repository/docker/eurobenchtest/pi_sbs_biomechanics

As indicated there, anyone can download the image, and then use it.
This is how we get the image on the eurobench server actually.

Now we have to bring your protocol description to the Eurobench website.
I'll tell you once done.

**Comment by dborro** [comment]
Ok.
If we have to do any change in the code, should we modify both repositories (private stepbystep and public eurobench)?

**Comment by aremazeilles** [comment]
You modify your repository, we check the cI process goes well, and then I will update the eurobench repo, and push a new docker image to the hub
